# 化妆品知识库问答机器人Pipeline项目 开发环境 Docker Compose 配置

version: '3.8'

services:
  # 主应用服务（开发模式）
  intent-agent-pipeline-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: intent-agent-pipeline-dev
    ports:
      - "8888:8000"
    env_file: # 会覆盖宿主机的变量
      - ../.env  # 显式指定.env文件
    environment:
      # 应用配置
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=debug
      - API_HOST=0.0.0.0
      - API_PORT=8000
      
      # # OpenAI配置 会从宿主机读取环境变量
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      # - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://openrouter.ai/api/v1}
      # - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o}
      
      # # 知识库配置
      # - KNOWLEDGE_API_URL=${KNOWLEDGE_API_URL:-http://117.50.252.245:3000}
      # - KNOWLEDGE_API_KEY=${KNOWLEDGE_API_KEY}
      
      # # LightRAG配置
      # - LIGHTRAG_API_URL=${LIGHTRAG_API_URL:-http://117.50.252.245:9621}
      # - LIGHTRAG_API_KEY=${LIGHTRAG_API_KEY}
      
      # # 搜索引擎配置
      # - SEARCH_ENGINE_API_KEY=${SEARCH_ENGINE_API_KEY}
      # - SEARCH_ENGINE_URL=${SEARCH_ENGINE_URL:-http://117.50.252.245:8081}
      
      # # Redis配置
      # - REDIS_HOST=redis-dev
      # - REDIS_PORT=6379
      # - REDIS_DB=0
      # - REDIS_PASSWORD=
      
      # 性能配置
      - MAX_WORKERS=5
      - REQUEST_TIMEOUT=60
      - STREAM_CHUNK_SIZE=512
    volumes:
      # 挂载源代码以支持热重载
      - ../app:/app/app
      - ../logs:/app/logs
      - ../data:/app/data
      - ../.env:/app/.env
    depends_on:
      - redis-dev
    restart: unless-stopped
    networks:
      - intent-agent-dev-network
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # Redis服务（开发环境）
  redis-dev:
    image: redis:7-alpine
    container_name: intent-agent-redis-dev
    ports:
      - "6380:6379"  # 使用不同端口避免冲突
    volumes:
      - redis_dev_data:/data
    restart: unless-stopped
    networks:
      - intent-agent-dev-network
    command: redis-server --appendonly yes

# 网络配置
networks:
  intent-agent-dev-network:
    driver: bridge

# 数据卷配置
volumes:
  redis_dev_data:
    driver: local

